name: SuperBuildBattle
main: io.github.galaipa.sbb.SuperBuildBattle
version: 12.1
author: Galaipa 
website: https://www.spigotmc.org/resources/super-build-battle.8775/
description: BuildBattle minigame plugin
softdepend: [WorldEdit,WorldGuard,Vault,PlayerPoints,Multiverse-Core]
commands:
  buildbattle:
    description: BuildBattle main command
    usage: /<command>  
    aliases: [bb]
  buildbattleadmin:
    description: BuildBattle main command
    usage: /<command>  
    aliases: [bbadmin]
permissions:
  bb.*:
        description: Gives access to all commands
        children:
            bb.join: true
  bb.user:
    description: Perm to use all user commands
    default: true
  bb.admin:
    description: Perm to use all admin commands
    default: op